"""生成可交互的 HTML 3D 预览页。

把网格数据内嵌为一个自包含 HTML 文件，使用 Three.js（CDN）渲染，
用户在任何浏览器中打开即可用鼠标拖拽旋转、滚轮缩放查看模型。

文件结构：HTML + 内嵌 JSON 顶点数据 + 少量样式与交互脚本。
"""

from __future__ import annotations

import json
from typing import Optional, Tuple

from .mesh import Mesh

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>3D 模型预览 - {title}</title>
<style>
  html, body {{ margin: 0; padding: 0; height: 100%; overflow: hidden; background: #0d1220; font-family: -apple-system, "PingFang SC", "Microsoft YaHei", sans-serif; }}
  #info {{
    position: fixed; top: 14px; left: 50%; transform: translateX(-50%);
    color: #e8eefc; font-size: 13px; letter-spacing: 0.5px;
    background: rgba(13, 18, 32, 0.72); padding: 8px 18px; border-radius: 20px;
    border: 1px solid rgba(120, 160, 255, 0.25); backdrop-filter: blur(6px);
    pointer-events: none; z-index: 10; white-space: nowrap;
  }}
  #badge {{
    position: fixed; bottom: 14px; right: 16px; color: rgba(200, 215, 255, 0.5);
    font-size: 11px; z-index: 10; pointer-events: none;
  }}
  .stats {{
    position: fixed; bottom: 14px; left: 16px; color: rgba(200, 215, 255, 0.7);
    font-size: 11px; z-index: 10; pointer-events: none; line-height: 1.6;
  }}
</style>
</head>
<body>
<div id="info">🖱️ 拖拽旋转 &nbsp;·&nbsp; 滚轮缩放 &nbsp;·&nbsp; 右键平移 — {title}</div>
<div class="stats">顶点 {verts} &nbsp;|&nbsp; 三角面 {faces} &nbsp;|&nbsp; 格式 {format}</div>
<div id="badge">Generated by AstrBot · 3D Model Factory</div>

<script src="https://unpkg.com/three@0.160.0/build/three.min.js"></script>
<script src="https://unpkg.com/three@0.160.0/examples/js/controls/OrbitControls.js"></script>
<script>
const MODEL = {data};

(function () {{
  const scene = new THREE.Scene();
  // 渐变背景
  const canvas = document.createElement('canvas'); canvas.width = 2; canvas.height = 512;
  const ctx = canvas.getContext('2d');
  const g = ctx.createLinearGradient(0, 0, 0, 512);
  g.addColorStop(0, '#182238'); g.addColorStop(1, '#0c1020');
  ctx.fillStyle = g; ctx.fillRect(0, 0, 2, 512);
  const bgTex = new THREE.CanvasTexture(canvas);
  scene.background = bgTex;

  // 灯光
  scene.add(new THREE.HemisphereLight(0xffffff, 0x223355, 0.9));
  const dir = new THREE.DirectionalLight(0xffffff, 1.2); dir.position.set(5, 8, 6); scene.add(dir);
  const fill = new THREE.DirectionalLight(0x88aaff, 0.35); fill.position.set(-6, 2, -4); scene.add(fill);

  // 网格
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(MODEL.positions, 3));
  geo.setAttribute('normal', new THREE.Float32BufferAttribute(MODEL.normals, 3));
  geo.setIndex(MODEL.faces);
  geo.computeBoundingSphere();
  const mat = new THREE.MeshStandardMaterial({{
    color: {color}, metalness: 0.15, roughness: 0.35,
    flatShading: true, side: THREE.DoubleSide
  }});
  const mesh = new THREE.Mesh(geo, mat);
  scene.add(mesh);

  // 自动取景
  const r = geo.boundingSphere.radius * 1.6 || 3;
  const camera = new THREE.PerspectiveCamera(45, innerWidth / innerHeight, 0.1, r * 100);
  camera.position.set(r * 1.1, r * 0.7, r * 1.4);
  camera.lookAt(0, 0, 0);

  // 辅助
  const grid = new THREE.GridHelper(r * 2.4, 20, 0x3a4a7a, 0x263252);
  grid.position.y = -r * 0.9; scene.add(grid);

  const renderer = new THREE.WebGLRenderer({{ antialias: true }});
  renderer.setSize(innerWidth, innerHeight);
  renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
  document.body.appendChild(renderer.domElement);

  const controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true; controls.dampingFactor = 0.08;
  controls.autoRotate = true; controls.autoRotateSpeed = 1.4;
  controls.target.set(0, 0, 0);

  addEventListener('resize', () => {{
    camera.aspect = innerWidth / innerHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(innerWidth, innerHeight);
  }});

  (function animate () {{
    requestAnimationFrame(animate);
    controls.update();
    renderer.render(scene, camera);
  }})();
}})();
</script>
</body>
</html>
"""


def generate_html_preview(
    mesh: Mesh,
    title: str = "3D Model",
    color: Tuple[int, int, int] = (0x44, 0xaa, 0xff),
    fmt: str = "stl",
) -> str:
    """生成自包含的 HTML 3D 预览页面字符串。"""
    verts = mesh.vertices.tolist()
    # 只保留被面引用的顶点，减小体积
    used = sorted(set(mesh.faces.ravel().tolist()))
    remap = {old: new for new, old in enumerate(used)}
    positions = [verts[i] for i in used]
    faces = [[remap[int(a)], remap[int(b)], remap[int(c)]] for a, b, c in mesh.faces.tolist()]
    normals = mesh.normals.tolist()

    data = {
        "positions": [round(v, 6) for p in positions for v in p],
        "normals": [round(v, 6) for n in normals for v in n],
        "faces": [int(x) for t in faces for x in t],
    }
    color_hex = "#%02x%02x%02x" % color
    html = _HTML_TEMPLATE.format(
        title=title,
        data=json.dumps(data, separators=(",", ":")),
        color=json.dumps(color_hex),
        verts=mesh.vertex_count,
        faces=mesh.face_count,
        format=fmt.upper(),
    )
    return html
